### ISSUE TITLE
Update Data Management Plan in Footer of SCOS Website

### ISSUE THREAD

**Issue by JulieMaterni** [SmartColumbusOS/monitoring#130]
AC:
- [ ] Update link to Data Management Plan in SCOS website footer to link to updated 2020 plan.

Updated Data Management Plan found here: 
https://smartcolumbusprogram.sharepoint.com/TaskEDeliverables/Forms/ContentType.aspx?id=%2FTaskEDeliverables%2FSCC%2DE%2DDataManagementPlan%2DUpdate%2Dv1%2Epdf&parent=%2FTaskEDeliverables&p=true&originalPath=aHR0cHM6Ly9zbWFydGNvbHVtYnVzcHJvZ3JhbS5zaGFyZXBvaW50LmNvbS9fbGF5b3V0cy8xNS9ndWVzdGFjY2Vzcy5hc3B4P2RvY2lkPTAxOThiYTA2NjI5ZjQ0ZjZlOTRiMjdmYzRiNjVlZGU1NCZhdXRoa2V5PUFSRC14N1lrMGdJXzRmTGJYVC0zTDRBJmV4cGlyYXRpb249MjAyMC0xMi0wM1QxOSUzYTUzJTNhNTEuMDAwWiZydGltZT0wRVBMQm1ORTJFZw

Joomla URL: https://www.smartcolumbusos.com/images/2020/PDF/SCC-E-DataManagementPlan-Update-v1.pdf

**Comment by jakeclark** [comment]
I can add to Joomla, will need to be added via discovery UI
