### ISSUE TITLE
helm chart missing poddisruptionbudgets resource.

### ISSUE THREAD

**Issue by dunson062786** [SmartColumbusOS/monitoring#85]
Prometheus is currently in a crash loop backoff 

<img width="1156" alt="Crash Loop Backoff" src="https://user-images.githubusercontent.com/1486284/66332397-9fb29c80-e902-11e9-949b-6d15853df883.png">

and it is caused by a helm chart missing poddisruptionbudgets resource.

helms default chart: https://github.com/helm/charts/blob/master/stable/prometheus/templates/kube-state-metrics-clusterrole.yaml

<img width="877" alt="poddisruptionbudgets" src="https://user-images.githubusercontent.com/1486284/66332061-d9cf6e80-e901-11e9-824d-6898a403a6c2.png">

<img width="1288" alt="Error" src="https://user-images.githubusercontent.com/1486284/66332446-c40e7900-e902-11e9-87b0-c2ff002d0b80.png">

**Comment by jeffgrunewald** [comment]
This would actually be that the kubernetes service that is attempting to monitor cluster resources doesn't have the API permissions assigned to its (cluster) role to list or view the the poddisruptionbudget resource.
