### ISSUE TITLE
Add ability to download private datasets

### ISSUE THREAD

**Issue by mcsearchin** [SmartColumbusOS/monitoring#95]
As a Discovery UI user
I would like to be able to click on the download button for a private dataset
and have it work

This bug was introduced by the switch to Auth0. The download button used to work for private datasets because we sent a cookie along with the request. We have removed cookie support from the API with the switch to Auth0, making this solution not work. There are a lot of different ways to solve this. Go to town.

Tech notes:
- Try not to use cookies, please
- Feel free to spike first
- As a part of this card, make sure to use full URL's instead of partial URL's if the API response includes a URL.
- General flow based on the spike and conversations with @jmorris-pillar: the download button will get a presigned URL which includes an HMAC token. The UI will then follow this presigned URL to download the dataset.

**Comment by ManApart** [comment]
I'm assuming a number of possible fixes could make LDAP no longer work. If we're still trying to support it, do we need to have an AC for making sure the solution doesn't break an LDAP-configured download?

**Comment by kennyatpillar** [comment]
Merged in AC from this card:
https://github.com/smartcitiesdata/smartcitiesdata/issues/464
